### ISSUE TITLE
[plugin.api.websocket][error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

### ISSUE THREAD

**Issue by Yesterday17** [streamlink/streamlink-appimage#1]
The same problem as https://github.com/niess/python-appimage/issues/24 ?

**Comment by bastimeyer** [comment]
This is not an AppImage packaging issue. Streamlink issues do not belong here. Also no debug log at all, which is useless.

**Comment by bastimeyer** [comment]
What do you expect anyone to do here if you don't even post anything useful at all, like the exact appimage you were using and the exact command you were running which led to the problem?

The error message you've posted is coming from Streamlink's websocket module, and the issue is a TLS/SSL certificate issue. Streamlink's AppImages bundle a Python install which is built from the official Python manylinux2014 docker images, and all the latest dependencies are bundled as well, including certifi for the necessary root certificates.

The issue you've linked is unrelated.

**Comment by Yesterday17** [comment]
The exception itself is self-explaining. Python (somehow) failed to get local issuer certificate. It's a CA issue, which does not exists in host environment at all.

**Comment by Yesterday17** [comment]
Appimage prepared all the dependencies, but the local ca list could not be retrived. Why the issue is unrelated?

**Comment by Yesterday17** [comment]
It seems the issue is actually unrelated, but the behavior is strange. I'll investigate it later to find out what has happened. Sorry for disturbing.

**Comment by bastimeyer** [comment]
Streamlink doesn't set any custom paths for the `cert` param of any session initialization or specific request made by `requests`, which means it defaults to the value which `certifi.where()` returns. `certify.where()` returns its locally bundled `cacert.pem` file. This should work even in cases of AppImages, where the squashfs gets mounted to a temporary location before execution, because `certify` uses relative file paths.

`requests` however allows you to override this file via the `REQUESTS_CA_BUNDLE` or `CURL_CA_BUNDLE` env vars.

**Comment by Yesterday17** [comment]
I tried to add `$SSL_CERT_FILE` manually with:

```bash
export SSL_CERT_FILE='path-to-cacert.pem'
```

And everything works now.

**Comment by bastimeyer** [comment]
Let me have a look. I was talking about `requests`, but `websocket-client` apparently doesn't use the bundled CA file.

**Comment by bastimeyer** [comment]
So there are two options to avoid having Streamlink use two different CA cert files:

1. Set OpenSSL's `SSL_CERT_FILE` env var with a value pointing towards the `cacert.pam` file bundled by `certifi` in the AppImage's `AppRun` and only make changes to the AppImage. Optionally also only set it if it's unset on the user's system, so custom values can still be set.
2. Update Streamlink's `WebsocketClient` and set the `ca_cert` parameter on the SSL options dict, with a default value of the `cacert.pam` file bundled by `certifi`, similar to all HTTP requests made by `requests`.
   https://github.com/streamlink/streamlink/commit/4c36d19d0b2173e4db186009177793b04c4de1b2

Since Streamlink shouldn't be using two different implementations regardless whether an AppImage is used or not, the second solution sounds like a better idea.
